import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";
import MobileMenu from "@/components/navbar/mobile-menu";
import MobileMenuToggler from "@/components/navbar/mobile-menu-toggler";
import { Overlay } from "@/components/navbar/overlay";

const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lateef Taiwo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "relative antialiased transition",
            jetbrainsMono.className
          )}
        >
          <ThemeProvider attribute="class" defaultTheme="light">
            <Navbar />
            <Overlay />
            <MobileMenu />
            <MobileMenuToggler />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </Providers>
  );
}
